### ISSUE TITLE
Undefined references if built with --enable-cluster

### ISSUE THREAD

**Issue by mrueg** [haiwen/ccnet#103]
`libtool: link: x86_64-pc-linux-gnu-gcc -march=native -O2 -pipe -Wl,-O1 -o ccnet-cserver server.o inner-session.o outer-session.o cluster-mgr.o server-session.o user-mgr.o group-mgr.o org-mgr.o recvlogin-proc.o recvlogout-proc.o ccnet-db.o session.o peer-mgr.o packet-io.o message.o perm-mgr.o log.o peer.o algorithms.o handshake.o processor.o getgateway.o connect-mgr.o message-manager.o proc-factory.o ccnet-config.o rpc-service.o peermgr-message.o sendmsg-proc.o rcvmsg-proc.o rcvcmd-proc.o putpubinfo-proc.o getpubinfo-proc.o keepalive2-proc.o mqserver-proc.o service-proxy-proc.o service-stub-proc.o rpcserver-proc.o threaded-rpcserver-proc.o echo-proc.o  -Wl,--as-needed ../../lib/.libs/libccnetd.a -levent -lssl -lcrypto -luuid -lsqlite3 -lpthread /usr/lib64/libsearpc.so -lgio-2.0 -lgobject-2.0 -lglib-2.0 -ljansson -lzdb
recvlogin-proc.o: In function `start':
recvlogin-proc.c:(.text+0xe4): undefined reference to `ccnet_user_manager_get_binding_email'
recvlogin-proc.c:(.text+0x14c): undefined reference to `ccnet_user_manager_add_binding'
recvlogout-proc.o: In function `start':
recvlogout-proc.c:(.text+0xcf): undefined reference to `ccnet_user_manager_get_binding_email'
recvlogout-proc.c:(.text+0xe5): undefined reference to `ccnet_user_manager_remove_one_binding'
proc-factory.o: In function `ccnet_proc_factory_new':
proc-factory.c:(.text+0x1f5): undefined reference to `ccnet_sendsessionkey_proc_get_type'
proc-factory.c:(.text+0x20c): undefined reference to `ccnet_recvsessionkey_proc_get_type'
proc-factory.c:(.text+0x223): undefined reference to `ccnet_sendskey2_proc_get_type'
proc-factory.c:(.text+0x23a): undefined reference to `ccnet_recvskey2_proc_get_type'
collect2: error: ld returned 1 exit status
Makefile:508: recipe for target 'ccnet-cserver' failed
make[3]: *** [ccnet-cserver] Error 1
make[3]: Leaving directory '/var/tmp/portage/net-libs/ccnet-5.0.2/work/ccnet-5.0.2/net/cluster'
Makefile:393: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/var/tmp/portage/net-libs/ccnet-5.0.2/work/ccnet-5.0.2/net'
Makefile:500: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/var/tmp/portage/net-libs/ccnet-5.0.2/work/ccnet-5.0.2'
Makefile:409: recipe for target 'all' failed
make: *** [all] Error 2`

**Comment by shoeper** [comment]
--enable-cluster is only part of the pro edition from Seafile.

**Comment by mrueg** [comment]
@shoeper Thanks for that information. It would be great to have this documented somewhere in the source code.
