### ISSUE TITLE
What about respecting LSB ?

### ISSUE THREAD

**Issue by computersalat** [haiwen/ccnet#26]
placing config files in /etc
placing logfiles in /var/log 
instead of heaving all in ./ ?

**Comment by jirutka** [comment]
+1

**Comment by computersalat** [comment]
@jirutka 
sorry, but doesn't make sense to keep this open

**Comment by jirutka** [comment]
It would make more sense to fix it...

**Comment by computersalat** [comment]
feel free to fix ... I am out.
